import type { ComponentType } from "react";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiNodedotjs,
  SiPython,
  SiTailwindcss,
  SiPostgresql,
  SiMongodb,
  SiDocker,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiPhp,
  SiLaravel,
  SiMysql,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiRedis,
  SiGraphql,
  SiFirebase,
  SiKubernetes,
  SiLinux,
  SiNginx,
  SiDjango,
  SiFlutter,
  SiFigma,
  SiWordpress,
  SiSass,
  SiRedux,
} from "react-icons/si";

export type IconKey = string;

export const ICON_REGISTRY: Record<string, ComponentType<{ size?: number; className?: string }>> = {
  SiHtml5,
  SiCss3: SiHtml5,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiPython,
  SiPhp,
  SiLaravel,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiTailwindcss,
  SiDocker,
  SiGit,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiRedis,
  SiGraphql,
  SiFirebase,
  SiKubernetes,
  SiLinux,
  SiNginx,
  SiDjango,
  SiFlutter,
  SiFigma,
  SiWordpress,
  SiSass,
  SiRedux,
};

export const ICON_OPTIONS = [
  { key: "SiHtml5", label: "HTML5" },
  { key: "SiCss3", label: "CSS3" },
  { key: "SiJavascript", label: "JavaScript" },
  { key: "SiTypescript", label: "TypeScript" },
  { key: "SiReact", label: "React" },
  { key: "SiNextdotjs", label: "Next.js" },
  { key: "SiNodedotjs", label: "Node.js" },
  { key: "SiPython", label: "Python" },
  { key: "SiPhp", label: "PHP" },
  { key: "SiLaravel", label: "Laravel" },
  { key: "SiPostgresql", label: "PostgreSQL" },
  { key: "SiMysql", label: "MySQL" },
  { key: "SiMongodb", label: "MongoDB" },
  { key: "SiRedis", label: "Redis" },
  { key: "SiTailwindcss", label: "Tailwind CSS" },
  { key: "SiDocker", label: "Docker" },
  { key: "SiKubernetes", label: "Kubernetes" },
  { key: "SiGit", label: "Git" },
  { key: "SiLinux", label: "Linux" },
  { key: "SiNginx", label: "Nginx" },
  { key: "SiVuedotjs", label: "Vue.js" },
  { key: "SiAngular", label: "Angular" },
  { key: "SiSvelte", label: "Svelte" },
  { key: "SiRedux", label: "Redux" },
  { key: "SiGraphql", label: "GraphQL" },
  { key: "SiFirebase", label: "Firebase" },
  { key: "SiDjango", label: "Django" },
  { key: "SiFlutter", label: "Flutter" },
  { key: "SiFigma", label: "Figma" },
  { key: "SiWordpress", label: "WordPress" },
  { key: "SiSass", label: "Sass" },
];

export function getIcon(key: string): ComponentType<{ size?: number; className?: string }> | null {
  return ICON_REGISTRY[key] ?? null;
}
