// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/quotes-section/QuotesSection.tsx": () => import("../components/mockups/quotes-section/QuotesSection.tsx")
};
